"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  ChevronLeft,
  ChevronRight,
  CheckCircle2,
  FileCode2,
  Sparkles,
} from "lucide-react";
import { HARNESS_API_BASE } from "@/lib/api";

type WizardState = {
  id: string;
  displayName: string;
  description: string;
  tagline: string;
  owner: string;
  sponsor: string;
  authMode: "Delegated" | "Application";
  delegatedScopes: string;
  appRoles: string;
  modelEndpoint: string;
  modelDeployment: string;
  modelApiVersion: string;
  mcpServers: string;
  kbSeedPath: string;
  sits: string;
};

const initial: WizardState = {
  id: "",
  displayName: "",
  description: "",
  tagline: "",
  owner: "admin@example.org",
  sponsor: "admin@example.org",
  authMode: "Delegated",
  delegatedScopes:
    "Mail.Read, Calendars.Read, Files.Read.All, Sites.Read.All, User.Read",
  appRoles: "Sites.Read.All",
  modelEndpoint: "https://your-foundry-account.cognitiveservices.azure.com/",
  modelDeployment: "gpt-4.1",
  modelApiVersion: "2024-08-01-preview",
  mcpServers: "",
  kbSeedPath: "",
  sits: "CreditCardNumber, IBAN, USSocialSecurityNumber, EmailAddress",
};

const steps = [
  { key: "identity", label: "Identity" },
  { key: "ownership", label: "Ownership" },
  { key: "permissions", label: "Permissions" },
  { key: "model", label: "Model" },
  { key: "tools", label: "Tools & KB" },
  { key: "review", label: "Review" },
];

export default function NewAgentWizard() {
  const [state, setState] = useState<WizardState>(initial);
  const [stepIdx, setStepIdx] = useState(0);
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<
    null | { ok: true; fileName: string } | { ok: false; error: string }
  >(null);

  const yamlPreview = useMemo(() => buildYaml(state), [state]);

  function set<K extends keyof WizardState>(k: K, v: WizardState[K]) {
    setState((s) => ({ ...s, [k]: v }));
  }

  async function submit() {
    setBusy(true);
    setResult(null);
    try {
      const fileName = `${slug(state.id || state.displayName)}.harness.yaml`;
      const r = await fetch(`${HARNESS_API_BASE}/api/blueprints`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ fileName, yaml: yamlPreview }),
      });
      if (!r.ok) {
        const text = await r.text();
        throw new Error(`HTTP ${r.status} ${r.statusText}: ${text}`);
      }
      setResult({ ok: true, fileName });
    } catch (e: unknown) {
      const err = e instanceof Error ? e.message : String(e);
      setResult({ ok: false, error: err });
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="p-8 grid grid-cols-1 xl:grid-cols-[1fr_460px] gap-8 min-h-[calc(100vh-64px)]">
      <div className="min-w-0">
        <div className="mb-6">
          <div className="chip chip-purple mb-2">blueprint wizard</div>
          <h1 className="text-2xl text-glow-purple">Define a new agent</h1>
          <p className="text-sm text-ink-dim mt-1">
            Produces a <code className="text-ink">*.harness.yaml</code>{" "}
            blueprint that the harness loads at startup. The matching{" "}
            <code className="text-ink">*.a365.json</code> is generated by{" "}
            <code className="text-ink">a365 develop register-blueprint</code> in
            the TUI demo.
          </p>
        </div>

        <div className="flex gap-1 mb-8 border-b border-navy-border">
          {steps.map((s, i) => (
            <button
              key={s.key}
              onClick={() => setStepIdx(i)}
              className={[
                "px-4 py-2 text-xs uppercase tracking-wider transition border-b-2",
                i === stepIdx
                  ? "border-neon-orange text-neon-orange"
                  : i < stepIdx
                  ? "border-transparent text-ink-dim hover:text-ink"
                  : "border-transparent text-ink-faint hover:text-ink-dim",
              ].join(" ")}
            >
              <span className="text-ink-faint mr-2">{i + 1}.</span>
              {s.label}
            </button>
          ))}
        </div>

        {stepIdx === 0 && (
          <Step title="Agent identity">
            <Field label="agent id" hint="kebab-case, used as filename + a365 id">
              <input
                value={state.id}
                onChange={(e) => set("id", e.target.value)}
                placeholder="forged-courier-three"
                className={inputCls}
              />
            </Field>
            <Field label="display name">
              <input
                value={state.displayName}
                onChange={(e) => set("displayName", e.target.value)}
                placeholder="Forged Courier Three"
                className={inputCls}
              />
            </Field>
            <Field label="tagline">
              <input
                value={state.tagline}
                onChange={(e) => set("tagline", e.target.value)}
                placeholder="One-liner the user sees in the hub."
                className={inputCls}
              />
            </Field>
            <Field label="description">
              <textarea
                value={state.description}
                onChange={(e) => set("description", e.target.value)}
                rows={4}
                placeholder="What does this agent do? Who is it for? What is it not for?"
                className={inputCls}
              />
            </Field>
          </Step>
        )}

        {stepIdx === 1 && (
          <Step title="Ownership">
            <p className="text-xs text-ink-dim mb-4">
              Owner is the human accountable for behavior; sponsor authorizes
              the agent to act inside the organization. Both appear in Entra
              Agent ID metadata.
            </p>
            <Field label="owner upn">
              <input
                value={state.owner}
                onChange={(e) => set("owner", e.target.value)}
                className={inputCls}
              />
            </Field>
            <Field label="sponsor upn">
              <input
                value={state.sponsor}
                onChange={(e) => set("sponsor", e.target.value)}
                className={inputCls}
              />
            </Field>
          </Step>
        )}

        {stepIdx === 2 && (
          <Step title="Permissions">
            <Field label="auth mode">
              <div className="flex gap-2">
                {(["Delegated", "Application"] as const).map((m) => (
                  <button
                    key={m}
                    type="button"
                    onClick={() => set("authMode", m)}
                    className={[
                      "px-3 py-2 text-xs uppercase tracking-wider rounded-sm border transition",
                      state.authMode === m
                        ? "border-neon-orange text-neon-orange bg-neon-orange/10"
                        : "border-navy-border text-ink-dim hover:text-ink",
                    ].join(" ")}
                  >
                    {m}
                  </button>
                ))}
              </div>
            </Field>
            {state.authMode === "Delegated" ? (
              <Field
                label="delegated scopes"
                hint="comma-separated Microsoft Graph scopes"
              >
                <textarea
                  rows={3}
                  value={state.delegatedScopes}
                  onChange={(e) => set("delegatedScopes", e.target.value)}
                  className={inputCls}
                />
              </Field>
            ) : (
              <Field
                label="application roles"
                hint="comma-separated app permissions"
              >
                <textarea
                  rows={3}
                  value={state.appRoles}
                  onChange={(e) => set("appRoles", e.target.value)}
                  className={inputCls}
                />
              </Field>
            )}
            <Field label="purview SITs to evaluate" hint="comma-separated">
              <input
                value={state.sits}
                onChange={(e) => set("sits", e.target.value)}
                className={inputCls}
              />
            </Field>
          </Step>
        )}

        {stepIdx === 3 && (
          <Step title="Model binding">
            <Field label="endpoint">
              <input
                value={state.modelEndpoint}
                onChange={(e) => set("modelEndpoint", e.target.value)}
                className={inputCls}
              />
            </Field>
            <Field label="deployment name">
              <input
                value={state.modelDeployment}
                onChange={(e) => set("modelDeployment", e.target.value)}
                className={inputCls}
                placeholder="gpt-4.1 / gpt-5.1 / text-embedding-3-small"
              />
            </Field>
            <Field label="api version">
              <input
                value={state.modelApiVersion}
                onChange={(e) => set("modelApiVersion", e.target.value)}
                className={inputCls}
              />
            </Field>
          </Step>
        )}

        {stepIdx === 4 && (
          <Step title="Tools & knowledge base">
            <Field
              label="MCP server endpoints"
              hint="one per line — http://host:port/mcp"
            >
              <textarea
                rows={3}
                value={state.mcpServers}
                onChange={(e) => set("mcpServers", e.target.value)}
                placeholder="http://localhost:3981/mcp"
                className={inputCls}
              />
            </Field>
            <Field
              label="local KB seed path"
              hint="optional — markdown folder to embed"
            >
              <input
                value={state.kbSeedPath}
                onChange={(e) => set("kbSeedPath", e.target.value)}
                placeholder="kb/agenticbank"
                className={inputCls}
              />
            </Field>
          </Step>
        )}

        {stepIdx === 5 && (
          <Step title="Review & save">
            <p className="text-xs text-ink-dim mb-3">
              The YAML on the right will be written to{" "}
              <code className="text-ink">
                blueprints/{slug(state.id || state.displayName)}.harness.yaml
              </code>{" "}
              and picked up on the next harness boot. The TUI demo registers it
              with Entra Agent ID via{" "}
              <code className="text-ink">a365 develop register-blueprint</code>.
            </p>
            {result && result.ok && (
              <div className="panel border-glow-orange p-4 text-sm text-ok mb-3 flex items-center gap-3">
                <CheckCircle2 className="w-5 h-5" />
                Saved <code className="text-ink">{result.fileName}</code>.
                <Link
                  href="/admin/blueprints"
                  className="ml-auto text-xs text-electric-purple-soft underline"
                >
                  view blueprints
                </Link>
              </div>
            )}
            {result && !result.ok && (
              <div className="panel p-4 text-sm text-cyber-pink mb-3">
                Failed to save: {result.error}
              </div>
            )}
            <button
              onClick={submit}
              disabled={busy}
              className="px-5 py-3 bg-neon-orange/15 border border-neon-orange/60 text-neon-orange hover:bg-neon-orange/25 transition rounded-sm text-sm uppercase tracking-wider disabled:opacity-50 inline-flex items-center gap-2"
            >
              <Sparkles className="w-4 h-4" />
              {busy ? "saving…" : "save blueprint draft"}
            </button>
          </Step>
        )}

        <div className="mt-8 flex items-center justify-between">
          <button
            disabled={stepIdx === 0}
            onClick={() => setStepIdx((i) => Math.max(0, i - 1))}
            className="px-3 py-2 text-xs uppercase tracking-wider text-ink-dim hover:text-ink disabled:opacity-30 inline-flex items-center gap-1"
          >
            <ChevronLeft className="w-3 h-3" /> back
          </button>
          <button
            disabled={stepIdx === steps.length - 1}
            onClick={() => setStepIdx((i) => Math.min(steps.length - 1, i + 1))}
            className="px-3 py-2 text-xs uppercase tracking-wider text-ink-dim hover:text-ink disabled:opacity-30 inline-flex items-center gap-1"
          >
            next <ChevronRight className="w-3 h-3" />
          </button>
        </div>
      </div>

      <aside className="min-w-0">
        <div className="sticky top-4">
          <div className="flex items-center gap-2 mb-3">
            <FileCode2 className="w-4 h-4 text-electric-purple-soft" />
            <h2 className="text-sm uppercase tracking-wider text-ink-dim">
              blueprint preview
            </h2>
          </div>
          <pre className="panel-glow scanline relative rounded-sm overflow-auto max-h-[calc(100vh-160px)] text-xs leading-relaxed p-4 text-ink whitespace-pre">
            {yamlPreview}
          </pre>
        </div>
      </aside>
    </div>
  );
}

function Step({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-5">
      <h2 className="text-lg text-glow-orange">{title}</h2>
      {children}
    </div>
  );
}

function Field({
  label,
  hint,
  children,
}: {
  label: string;
  hint?: string;
  children: React.ReactNode;
}) {
  return (
    <label className="block">
      <div className="text-xs uppercase tracking-wider text-ink-faint mb-1">
        {label}
        {hint && (
          <span className="ml-2 text-ink-faint normal-case tracking-normal lowercase">
            — {hint}
          </span>
        )}
      </div>
      {children}
    </label>
  );
}

const inputCls =
  "w-full bg-navy-deep/80 border border-navy-border focus:border-neon-orange/60 focus:outline-none focus:shadow-[0_0_12px_rgba(255,140,0,0.15)] rounded-sm px-3 py-2 text-sm text-ink placeholder:text-ink-faint font-mono";

function slug(s: string): string {
  return (s || "agent")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 60);
}

function buildYaml(s: WizardState): string {
  const id = slug(s.id || s.displayName || "new-agent");
  const items = (str: string) =>
    str.split(/[\n,]+/).map((x) => x.trim()).filter(Boolean);
  const sits = items(s.sits);
  const mcpLines = items(s.mcpServers);
  const perms =
    s.authMode === "Delegated"
      ? `permissions:
  delegated:
    - resource: https://graph.microsoft.com
      scopes:
${items(s.delegatedScopes).map((x) => `        - ${x}`).join("\n") || "        - User.Read"}
  application: []`
      : `permissions:
  delegated: []
  application:
    - resource: https://graph.microsoft.com
      roles:
${items(s.appRoles).map((x) => `        - ${x}`).join("\n") || "        - Sites.Read.All"}`;
  const mcp = mcpLines.length
    ? `mcpServers:
${mcpLines
  .map(
    (m, i) => `  - id: mcp_${i + 1}
    scope: local
    endpoint: ${m}`
  )
  .join("\n")}`
    : `mcpServers: []`;

  return `apiVersion: customagentharness/v1
kind: AgentBlueprint
metadata:
  id: ${id}
  displayName: ${s.displayName || id}
identity:
  displayName: ${s.displayName || id}
  description: |
    ${(s.description || "").split("\n").join("\n    ")}
  tagline: ${s.tagline || ""}
ownership:
  owner: ${s.owner}
  sponsor: ${s.sponsor}
authMode: ${s.authMode}
${perms}
model:
  endpoint: ${s.modelEndpoint}
  deploymentName: ${s.modelDeployment}
  apiVersion: ${s.modelApiVersion}
${mcp}
contentProtection:
  sensitiveInformationTypes:
${sits.map((x) => `    - ${x}`).join("\n") || "    - EmailAddress"}
${s.kbSeedPath ? `knowledgeBase:\n  seedPath: ${s.kbSeedPath}\n` : ""}`;
}
